/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUser { 
    id: string;
    username: string;
    role: AdminUser.RoleEnum;
    createdAt: string;
    updatedAt: string;
}
export namespace AdminUser {
    export const RoleEnum = {
        User: 'USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


