/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Uniform error shape. `code` drives client-side i18n; `message` is fallback/diagnostic text only.
 */
export interface ApiError { 
    code: string;
    message: string;
    field?: string | null;
    /**
     * Set only for 409 UNIQUE_VIOLATION — the id of the existing live row that conflicts.
     */
    conflictingId?: string | null;
}

