/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PitchLog } from './pitchLog';


/**
 * documentation/Features/Mászónapló.md \"Entitás — AscentAttempt\" — one logged attempt on a problem / route within a ClimbingSession. Only ever saved nested inside a ClimbingSession (documentation/Architektúra/Backend.md \"Nested aggregate PUT\"), but its own sync row. `deleted` is ONLY for the parent session\'s cascade soft-delete and the nested-PUT tree diff: an attempt dropped from the incoming `attempts` array is set `deleted = true` server-side (the client does not flag it). The `colorBandId` / `indoorRouteId` / `routeId` / `boulderProblemId` refs are optional soft links — the `*Name` / `color*` / `gradeRange` snapshot fields are what the napló renders. Which fields apply follows the parent session\'s `locationType` + `discipline` (enforced client-side).
 */
export interface AscentAttempt { 
    id: string;
    sessionId: string;
    isSuccess: boolean;
    /**
     * Raw grade text the user typed; parsed client-side, stored verbatim.
     */
    userRawInput?: string | null;
    /**
     * Resolved matrix index (documentation/Subfeatures/Nehézségi szint skálája (konverziós mátrix).md); the client computes it, the server never recomputes.
     */
    absoluteDifficultyIndex?: number | null;
    /**
     * Only meaningful when `isSuccess`; the context whitelist is enforced client-side.
     */
    ascentStyle?: AscentAttempt.AscentStyleEnum | null;
    /**
     * Rope only (indoor hides TRAD client-side); null for boulder.
     */
    safetyStyle?: AscentAttempt.SafetyStyleEnum | null;
    /**
     * Optional; on an unsuccessful attempt.
     */
    failurePoint?: string | null;
    /**
     * Number of goes on this problem / route, context-independent. Statistics (volume, success rate) only — NOT the duration fallback, which counts logged attempt rows.
     */
    attemptCount?: number | null;
    /**
     * Indoor boulder: → GymColorBand. Soft link.
     */
    colorBandId?: string | null;
    colorName?: string | null;
    hexColor?: string | null;
    /**
     * Colour-band grade range snapshot, e.g. \"6A–6B\".
     */
    gradeRange?: string | null;
    /**
     * Indoor rope: → IndoorRoute. Soft link.
     */
    indoorRouteId?: string | null;
    /**
     * Outdoor rope: → Route. Soft link.
     */
    routeId?: string | null;
    /**
     * Outdoor boulder: → BoulderProblem. Soft link.
     */
    boulderProblemId?: string | null;
    /**
     * Snapshot name for whichever route / problem was selected (or an ad-hoc name).
     */
    routeName?: string | null;
    /**
     * Rope: attempt length. Default from the route / gym wall height, resolved client-side.
     */
    lengthInMeters?: number | null;
    notes?: string | null;
    orderIndex: number;
    /**
     * Outdoor multi-pitch rope only; empty otherwise.
     */
    pitches: Array<PitchLog>;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace AscentAttempt {
    export const AscentStyleEnum = {
        Onsight: 'ONSIGHT',
        Flash: 'FLASH',
        Redpoint: 'REDPOINT'
    } as const;
    export type AscentStyleEnum = typeof AscentStyleEnum[keyof typeof AscentStyleEnum];
    export const SafetyStyleEnum = {
        Toprope: 'TOPROPE',
        Lead: 'LEAD',
        Trad: 'TRAD'
    } as const;
    export type SafetyStyleEnum = typeof SafetyStyleEnum[keyof typeof SafetyStyleEnum];
}


