/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Features/AYCM tracker.md — the 1:1-per-user AYCM settings singleton. Holds only the optional link to a RecurringExpense (the monthly pass). No amount of its own; no FK to recurring_expense (loose coupling — the client checks whether the linked row still counts).
 */
export interface AycmSettings { 
    id: string;
    /**
     * The linked RecurringExpense (the monthly pass), or null when nothing is linked.
     */
    linkedRecurringExpenseId?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

