/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/AYCM Check-In.md — one AYCM entry for a calendar day. Flat, user-owned. The row is a snapshot taken at save time: the server stores partnerName / ruleId / ruleLabel / listPriceHuf / coPaymentHuf / visitValueHuf exactly as the client sends them and never re-runs the price-rule match. visitValueHuf equals listPriceHuf; coPaymentHuf is metadata only. At most one live row per user per checkInDate (409 UNIQUE_VIOLATION otherwise). Past, today and future dates are all allowed.
 */
export interface AycmCheckIn { 
    id: string;
    /**
     * Client calendar day (YYYY-MM-DD). Past, today and future are all valid.
     */
    checkInDate: string;
    /**
     * \"HH:mm\", minute 0..1439 — never \"24:00\".
     */
    checkInTime: string;
    /**
     * The chosen partner. No FK to a live partner — a deleted partner\'s uuid stays for stats.
     */
    partnerId: string;
    /**
     * Snapshot of the partner\'s live name at save time.
     */
    partnerName: string;
    /**
     * Snapshot; the matched price rule\'s id, or null when no band covered the time.
     */
    ruleId?: string | null;
    /**
     * Snapshot; displayLabel of the matched rule, or \"\" / \"—\" when there was no match.
     */
    ruleLabel: string;
    /**
     * Snapshot; 0 when no band matched.
     */
    listPriceHuf: number;
    /**
     * Snapshot metadata; never added to visitValueHuf.
     */
    coPaymentHuf: number;
    /**
     * Snapshot; equals listPriceHuf (AYCM tracker.md).
     */
    visitValueHuf: number;
    notes?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

