/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Features/Biciklizés napló.md — one logged bike ride (\"egy napló = egy út\"). No start/end time, only a calendar date + a manual durationMinutes. No kcal / body-weight field: the aznapi activityExtraKcal contribution is a pure client calculation with the canonical MET formula (documentation/Features/Tápérték kalkulátor.md). distanceKm / elevationGainMeters are log/statistics only (and a speed-based MET hint in the UI) — never part of the kcal formula.
 */
export interface BikeRideLog { 
    id: string;
    /**
     * Calendar date in the client\'s TZ — the aznapi activityExtraKcal bucket. No time-of-day.
     */
    date: string;
    /**
     * Whole minutes, > 0. The only kcal input alongside intensity.
     */
    durationMinutes: number;
    /**
     * MET source — CITY 4.0, STATIONARY 6.0, ROAD_LEISURE 6.8, MOUNTAIN_TRAIL 8.5, ROAD_VIGOROUS 10.0. A single required choice.
     */
    intensity: BikeRideLog.IntensityEnum;
    /**
     * Optional; log / statistics only, plus the UI avg-speed MET hint. Never in the kcal formula.
     */
    distanceKm?: number | null;
    /**
     * Optional; log / statistics only. Never in the kcal formula.
     */
    elevationGainMeters?: number | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace BikeRideLog {
    export const IntensityEnum = {
        City: 'CITY',
        Stationary: 'STATIONARY',
        RoadLeisure: 'ROAD_LEISURE',
        MountainTrail: 'MOUNTAIN_TRAIL',
        RoadVigorous: 'ROAD_VIGOROUS'
    } as const;
    export type IntensityEnum = typeof IntensityEnum[keyof typeof IntensityEnum];
}


