/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Outdoor boulder admin.md — an optional user-owned boulder problem master under a Sector (\"Opcionális master\"); the napló can also create ad-hoc problems without one. `guidebookGrade` is the raw guidebook string, parsed client-side (no matrix index column). The sector link is fixed at create time.
 */
export interface BoulderProblem { 
    id: string;
    sectorId: string;
    name: string;
    guidebookGrade: string;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

