/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CuratedRouteActivityType } from './curatedRouteActivityType';
import { HikeRouteDay } from './hikeRouteDay';
import { CuratedRouteDifficulty } from './curatedRouteDifficulty';


/**
 * Admin upsert kérés (backlog/tura-utvonaltervezo/103-... 2.5 fázis, POST /api/admin/tura/curated-routes — X-Admin-Api-Key). Idempotens: a megadott id-re a teljes rekordot lecseréli. A táv/szint/idő-becslést a szerver maga számolja ki a coordinates-ból (RouteMetricsService) — az admin nem adja meg.
 */
export interface CuratedRouteUpsertRequest { 
    id: string;
    name: string;
    description?: string | null;
    difficulty: CuratedRouteDifficulty;
    activityType: CuratedRouteActivityType;
    coordinates: Array<Array<number>>;
    days?: Array<HikeRouteDay> | null;
}
export namespace CuratedRouteUpsertRequest {
}


