/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CuratedRouteActivityType } from './curatedRouteActivityType';
import { HikeRouteDay } from './hikeRouteDay';
import { CuratedRouteDifficulty } from './curatedRouteDifficulty';


/**
 * backlog/tura-utvonaltervezo/103-... 2.5 fázis — admin-szerkesztett vagy OSM-eredetű ajánlott túra. Kizárólag saját/admin tartalom, nem közösségi feltöltés (ld. archive/110-... dropped). Megosztott referenciaadat, mint a TrailSegment: nincs user_id, nincs deleted tombstone, nem az /api/sync/changes csatornán megy — a dedikált, szűrhető GET /api/tura/curated-routes listával érhető el.
 */
export interface CuratedRoute { 
    id: string;
    name: string;
    description?: string | null;
    difficulty: CuratedRouteDifficulty;
    activityType: CuratedRouteActivityType;
    /**
     * Az útvonal vonalgeometriája, [lon, lat] pontsorozatként.
     */
    coordinates: Array<Array<number>>;
    /**
     * backlog/tura-utvonaltervezo/103-... — szakaszokra bontás/éjszakázó pontok többnapos ajánlott túrákhoz; üres vagy hiányzó tömb = egynapos túra. Ugyanaz a HikeRouteDay DTO, mint a felhasználó saját útvonalainál.
     */
    days?: Array<HikeRouteDay> | null;
    /**
     * A szerver számolja ki (RouteMetricsService) admin upsertkor, a coordinates-ból.
     */
    distanceMeters: number;
    elevationGainMeters: number;
    elevationLossMeters: number;
    estimatedDurationMinutes: number;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace CuratedRoute {
}


