/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Gyakorlat.md — user-owned exercise master catalog entry. `kind` determines which set-entry input fields the Edzésnapló shows; `category` drives picker chips and statistics. Edzésnapló entries snapshot name/category/kind, so editing or soft-deleting a row here never rewrites past sessions.
 */
export interface Exercise { 
    id: string;
    name: string;
    category: Exercise.CategoryEnum;
    kind: Exercise.KindEnum;
    defaultRestTimeSeconds?: number | null;
    isFavorite: boolean;
    equipment?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace Exercise {
    export const CategoryEnum = {
        Chest: 'CHEST',
        Back: 'BACK',
        Legs: 'LEGS',
        Shoulders: 'SHOULDERS',
        Arms: 'ARMS',
        Core: 'CORE',
        ForearmFingers: 'FOREARM_FINGERS',
        FullBody: 'FULL_BODY'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
    export const KindEnum = {
        WeightedReps: 'WEIGHTED_REPS',
        BodyweightReps: 'BODYWEIGHT_REPS',
        IsometricTime: 'ISOMETRIC_TIME',
        HangboardPinch: 'HANGBOARD_PINCH',
        CardioTimeDist: 'CARDIO_TIME_DIST'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


