/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Élelmiszerek.md — shared/global food catalog entry (no per-user ownership). Only name is required; every other field may be absent (partial catalog items are allowed).
 */
export interface Food { 
    id: string;
    name: string;
    store?: string | null;
    brand?: string | null;
    barcode?: string | null;
    note?: string | null;
    priceHuf?: number | null;
    netAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md quantity unit: cs, g, dkg, kg, l, dl, cl, or ml.
     */
    netUnit?: string | null;
    /**
     * backlog/063 — darab-definíció: \"1 darab = pieceAmount pieceUnit\" (fraction allowed, e.g. 1/6 csomag). Null together with pieceUnit means \"1 darab = 1 csomag\". Both set or both null.
     */
    pieceAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md quantity unit for the darab-definíció: g, dkg, kg, ml, cl, dl, l, or cs. `db` is forbidden here (it would be circular).
     */
    pieceUnit?: string | null;
    energyKcal?: number | null;
    fatG?: number | null;
    fatSaturatedG?: number | null;
    fatUnsaturatedG?: number | null;
    fatTransG?: number | null;
    carbsG?: number | null;
    carbsSugarsG?: number | null;
    carbsComplexG?: number | null;
    carbsFiberG?: number | null;
    proteinG?: number | null;
    saltG?: number | null;
    sodiumG?: number | null;
    chlorideG?: number | null;
    shelfRoomAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md duration unit: perc, óra, nap, hét, hó, or év.
     */
    shelfRoomUnit?: string | null;
    shelfFridgeAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md duration unit: perc, óra, nap, hét, hó, or év.
     */
    shelfFridgeUnit?: string | null;
    shelfFreezerAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md duration unit: perc, óra, nap, hét, hó, or év.
     */
    shelfFreezerUnit?: string | null;
    shelfAfterOpeningAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md duration unit: perc, óra, nap, hét, hó, or év.
     */
    shelfAfterOpeningUnit?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

