/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElevationProfilePoint } from './elevationProfilePoint';


/**
 * backlog/tura-utvonaltervezo/103-... 2.1 fázis — kézzel rajzolt, user-owned túraútvonal. Teljesen offline-szinkronizált (ellentétben a megosztott TrailSegment-tel).
 */
export interface HikeRoute { 
    id: string;
    name: string;
    /**
     * Az útvonal vonalgeometriája, [lon, lat] pontsorozatként (waypointok, rajzolási sorrendben).
     */
    coordinates: Array<Array<number>>;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    /**
     * backlog/tura-utvonaltervezo/103-... 2.3 fázis. A kliens tölti ki a /api/tura/route-metrics hívás eredményéből mentéskor; null, ha a metrika-számítás még nem történt meg (pl. az elevation API akkor nem volt elérhető) — a HikeRoute enélkül is menthető/szinkronizálható.
     */
    distanceMeters?: number | null;
    elevationGainMeters?: number | null;
    elevationLossMeters?: number | null;
    estimatedDurationMinutes?: number | null;
    elevationProfile?: Array<ElevationProfilePoint> | null;
}

