/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * backlog/tura-utvonaltervezo/103-... 2.1 fázis — kézzel rajzolt, user-owned túraútvonal. Teljesen offline-szinkronizált (ellentétben a megosztott TrailSegment-tel).
 */
export interface HikeRoute { 
    id: string;
    name: string;
    /**
     * Az útvonal vonalgeometriája, [lon, lat] pontsorozatként (waypointok, rajzolási sorrendben).
     */
    coordinates: Array<Array<number>>;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

