/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Indoor köteles admin.md — an optional fixed indoor-route catalogue entry (\"fix termi út katalógus\"). `absoluteDifficultyIndex` comes from the client\'s matrix (documentation/Subfeatures/Nehézségi szint skálája (konverziós mátrix).md); the server stores, never recomputes it.
 */
export interface IndoorRoute { 
    id: string;
    gymId: string;
    name: string;
    discipline: IndoorRoute.DisciplineEnum;
    grade: string;
    absoluteDifficultyIndex: number;
    /**
     * Free-text sector / wall-strip label.
     */
    sector?: string | null;
    /**
     * backlog/079 — optional guidebook / topo ordinal (\"12\", \"5/a\", \"5b\"). Gym-scoped, not unique. Clients order route pickers by a natural (numeric-prefix + letter) sort on this, falling back to name; the server never orders by it.
     */
    topoNumber?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace IndoorRoute {
    export const DisciplineEnum = {
        Boulder: 'BOULDER',
        Rope: 'ROPE'
    } as const;
    export type DisciplineEnum = typeof DisciplineEnum[keyof typeof DisciplineEnum];
}


