/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Élet tervek.md — user-owned long-term life goal. Not unique by title (multiple identical titles allowed), not a Naptár producer in the MVP.
 */
export interface LifePlan { 
    id: string;
    title: string;
    notes?: string | null;
    status: LifePlan.StatusEnum;
    /**
     * Client calendar day, list-display only — never emitted to Naptár.
     */
    targetDate?: string | null;
    /**
     * Client-computed side effect of a status change (set on any -> DONE, cleared on DONE -> other). Must be present iff status is DONE — the server rejects a contradicting pair with 400.
     */
    completedAt?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace LifePlan {
    export const StatusEnum = {
        Planned: 'PLANNED',
        InProgress: 'IN_PROGRESS',
        Done: 'DONE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


