/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Sablonok.md — a GearItem reference inside a PackingTemplate, own sync entity.
 */
export interface PackingTemplateItem { 
    id: string;
    templateId: string;
    gearItemId: string;
    sortOrder: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

