/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PackingTemplateItem } from './packingTemplateItem';


/**
 * documentation/Architektúra/Backend.md \"Nested aggregate PUT\": PackingTemplate + its PackingTemplateItem rows saved/read as one tree. `items` always lists every row currently in the DB for this template, live or soft-deleted — the client\'s outbox apply step needs the tombstoned ones too, to clear their local dirty flag (the client always filters `deleted = false` itself when rendering).
 */
export interface PackingTemplateDetail { 
    id: string;
    name: string;
    notes?: string | null;
    deleted: boolean;
    items: Array<PackingTemplateItem>;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

