/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Pakolás.md — a GearItem reference inside a PackingSession, with a packing status. Own sync entity with standalone CRUD-ish endpoints (status/sortOrder changes are frequent, so they are NOT part of a nested session save — see PackingSession.yaml\'s neighboring paths file for the reasoning).
 */
export interface PackingSessionItem { 
    id: string;
    sessionId: string;
    gearItemId: string;
    status: PackingSessionItem.StatusEnum;
    sortOrder: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace PackingSessionItem {
    export const StatusEnum = {
        NotPacked: 'NOT_PACKED',
        KnownLocation: 'KNOWN_LOCATION',
        Prepared: 'PREPARED',
        WearOnDeparture: 'WEAR_ON_DEPARTURE',
        BuyOnTheWay: 'BUY_ON_THE_WAY',
        Packed: 'PACKED',
        NotNeeded: 'NOT_NEEDED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


