/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Outdoor köteles napló.md \"PitchLog\" — optional per-pitch breakdown for an outdoor multi-pitch rope attempt. Only ever saved nested inside a ClimbingSession (documentation/Architektúra/Backend.md \"Nested aggregate PUT\"), but its own sync row (own tombstones, own delta pull entries). `isLead = false` marks a following climber (active MET ×0.8 in the client kcal). If the list is empty the attempt\'s own `lengthInMeters` and grade stand for the whole route.
 */
export interface PitchLog { 
    id: string;
    attemptId: string;
    pitchNumber: number;
    /**
     * false = seconding this pitch (active MET ×0.8 in the client kcal).
     */
    isLead: boolean;
    /**
     * Raw grade text for this pitch; parsed client-side, stored verbatim.
     */
    rawGrade?: string | null;
    /**
     * Resolved matrix index for this pitch; the client computes it.
     */
    absoluteDifficultyIndex?: number | null;
    lengthInMeters?: number | null;
    orderIndex: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

