/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeIngredient } from './recipeIngredient';


/**
 * documentation/Subfeatures/Recept.md — shared/global catalog, no per-user ownership (mirrors Food). documentation/Architektúra/Backend.md \"Nested aggregate PUT\": Recipe + its RecipeIngredient rows saved/read as one tree, on every endpoint including the plain list — `ingredients` always lists every row for this recipe, live or soft-deleted, so the client\'s outbox apply step and the ingredient-set duplicate pre-check both see the full picture (the client filters `deleted = false` itself when rendering or summing).
 */
export interface Recipe { 
    id: string;
    name: string;
    note?: string | null;
    deleted: boolean;
    ingredients: Array<RecipeIngredient>;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

