/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Outdoor boulder admin.md — a user-owned sector under a Crag. `defaultAspect` is the default wall orientation (\"fekvés\") as an 8-wind compass token, inherited by routes and the outdoor napló. The crag link is fixed at create time.
 */
export interface Sector { 
    id: string;
    cragId: string;
    name: string;
    /**
     * backlog/068 — default wall aspect (\"fekvés\") as an 8-wind compass token, inherited by routes and the outdoor napló. `null` = unknown / not given.
     */
    defaultAspect?: Sector.DefaultAspectEnum | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace Sector {
    export const DefaultAspectEnum = {
        N: 'N',
        Ne: 'NE',
        E: 'E',
        Se: 'SE',
        S: 'S',
        Sw: 'SW',
        W: 'W',
        Nw: 'NW'
    } as const;
    export type DefaultAspectEnum = typeof DefaultAspectEnum[keyof typeof DefaultAspectEnum];
}


