/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Bevásárlólista írás.md \"Tétel hozzáadása\" — one polymorphic item on a ShoppingList. `type` selects which of the per-type fields apply: FOOD uses `foodId` + `quantityAmount` + `quantityUnit` (both required); NON_FOOD uses `name` (required) + optional `note` (free text: store/comment/other) + optional `quantityAmount`/`quantityUnit`. Unused fields for a given type are omitted/null.
 */
export interface ShoppingListItem { 
    id: string;
    shoppingListId: string;
    type: ShoppingListItem.TypeEnum;
    foodId?: string | null;
    name?: string | null;
    note?: string | null;
    quantityAmount?: number | null;
    /**
     * documentation/Architektúra/Mennyiség mező.md quantity unit: db, g, dkg, kg, l, dl, cl, or ml.
     */
    quantityUnit?: string | null;
    /**
     * documentation/Subfeatures/Bevásárlólista írás.md \"pipa\" — UI-only until Bevásárlás teljesítve runs.
     */
    checked: boolean;
    sortOrder: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace ShoppingListItem {
    export const TypeEnum = {
        Food: 'FOOD',
        NonFood: 'NON_FOOD'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


