/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Bevásárlás teljesítve.md response for a successful completion.
 */
export interface ShoppingListCompleteResponse { 
    archivedListId: string;
    /**
     * Echoes the client-supplied `storageEntryIds` back — confirmation, not newly minted ids.
     */
    createdStorageEntryIds: Array<string>;
    /**
     * Echoes `newActiveList.id` back when a new list was created, else null.
     */
    newActiveListId?: string | null;
}

