/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingListItem } from './shoppingListItem';


/**
 * documentation/Subfeatures/Bevásárlólista írás.md — per-user active shopping list. documentation/Architektúra/Backend.md \"Nested aggregate PUT\": ShoppingList + its ShoppingListItem rows saved/read as one tree, on every endpoint including the plain list — `items` always lists every row for this list, live or soft-deleted (client filters `deleted = false` itself when rendering or summing). `status`/`completedAt` are read-only in this API version — only the future Bevásárlás teljesítve `POST .../complete` endpoint transitions a list to ARCHIVED.
 */
export interface ShoppingList { 
    id: string;
    name?: string | null;
    readonly status?: ShoppingList.StatusEnum;
    readonly completedAt?: string | null;
    items: Array<ShoppingListItem>;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace ShoppingList {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Archived: 'ARCHIVED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


