/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingListCompleteNewList } from './shoppingListCompleteNewList';
import { ShoppingListCompleteFoodEntry } from './shoppingListCompleteFoodEntry';


/**
 * documentation/Subfeatures/Bevásárlás teljesítve.md request body for `POST /api/shopping-lists/{id}/complete`. `checkedFoodEntries` carries one entry per **checked FOOD** item currently on the list (checked/unchecked state and non-FOOD items are already persisted from the list\'s own saves — this body only adds what completion itself needs).
 */
export interface ShoppingListCompleteRequest { 
    checkedFoodEntries: Array<ShoppingListCompleteFoodEntry>;
    newActiveList?: ShoppingListCompleteNewList;
}

