/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Élelmiszer tárolás.md — a single per-user home-storage item referencing the (global) food catalog. Each row is independent (no merging by food+location+expiry). The \"felbontás\" expiry recompute and meal-time consumption deduction are client-side business logic (documentation/Architektúra/Backend-offline first.md) — the server just stores whatever full record it\'s sent.
 */
export interface StoredFood { 
    id: string;
    foodId: string;
    quantityAmount: number;
    /**
     * documentation/Architektúra/Mennyiség mező.md quantity unit: db, g, dkg, kg, l, dl, cl, or ml.
     */
    quantityUnit: string;
    storageLocation: StoredFood.StorageLocationEnum;
    expiresOn: string;
    opened: boolean;
    openedAt?: string | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace StoredFood {
    export const StorageLocationEnum = {
        Room: 'ROOM',
        Fridge: 'FRIDGE',
        Freezer: 'FREEZER'
    } as const;
    export type StorageLocationEnum = typeof StorageLocationEnum[keyof typeof StorageLocationEnum];
}


