/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Features/Úszás napló.md — one logged swim session (\"egy napló = egy edzés\"). No start/end time, only a calendar date + a manual durationMinutes. No kcal / body-weight field: the aznapi activityExtraKcal contribution is a pure client calculation with the canonical MET formula (documentation/Features/Tápérték kalkulátor.md). Pool length / lap count / distance are log/statistics only — never part of the kcal formula.
 */
export interface SwimLog { 
    id: string;
    /**
     * Calendar date in the client\'s TZ — the aznapi activityExtraKcal bucket. No time-of-day.
     */
    date: string;
    /**
     * Whole minutes, > 0. The only kcal input alongside intensity.
     */
    durationMinutes: number;
    /**
     * MET source — CASUAL/BREASTSTROKE/MIXED 5.5, BACKSTROKE 7.0, CRAWL_FREESTYLE 8.0, OPEN_WATER 9.5, BUTTERFLY/VIGOROUS 11.0. A single required choice — no separate strokeType.
     */
    intensity: SwimLog.IntensityEnum;
    /**
     * Pool length for a pool session (typical 25 / 50). Paired with lapCount — if one is present the other is required. Must be null for OPEN_WATER.
     */
    poolLengthMeters?: number | null;
    /**
     * One lap = one one-way length (not there-and-back). Paired with poolLengthMeters. Must be null for OPEN_WATER.
     */
    lapCount?: number | null;
    /**
     * Computed as poolLengthMeters × lapCount when both are present (the server overwrites whatever was sent). For OPEN_WATER it is an optional manually-entered value.
     */
    distanceMeters?: number | null;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace SwimLog {
    export const IntensityEnum = {
        Casual: 'CASUAL',
        Breaststroke: 'BREASTSTROKE',
        Backstroke: 'BACKSTROKE',
        CrawlFreestyle: 'CRAWL_FREESTYLE',
        OpenWater: 'OPEN_WATER',
        Butterfly: 'BUTTERFLY',
        Vigorous: 'VIGOROUS',
        Mixed: 'MIXED'
    } as const;
    export type IntensityEnum = typeof IntensityEnum[keyof typeof IntensityEnum];
}


