/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 1:1 per user. Every field except id is optional — an incomplete profile is a valid, saveable state.
 */
export interface UserProfile { 
    id: string;
    birthDate?: string | null;
    sex?: UserProfile.SexEnum | null;
    heightCm?: number | null;
    currentWeightKg?: number | null;
    goal?: UserProfile.GoalEnum | null;
    /**
     * Required on save when goal is FAT_LOSS or WEIGHT_GAIN; ignored when goal is MAINTENANCE.
     */
    kgPerWeek?: number | null;
    grossMonthlySalaryHuf?: number | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace UserProfile {
    export const SexEnum = {
        Male: 'MALE',
        Female: 'FEMALE'
    } as const;
    export type SexEnum = typeof SexEnum[keyof typeof SexEnum];
    export const GoalEnum = {
        FatLoss: 'FAT_LOSS',
        Maintenance: 'MAINTENANCE',
        WeightGain: 'WEIGHT_GAIN'
    } as const;
    export type GoalEnum = typeof GoalEnum[keyof typeof GoalEnum];
}


