/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkoutSetEntry } from './workoutSetEntry';


/**
 * documentation/Subfeatures/Edzésnapló.md \"Entitás — WorkoutExerciseEntry\" — one exercise block on a WorkoutSession. `exerciseName` / `exerciseCategory` / `exerciseKind` are a SNAPSHOT taken at save time; a later rename or soft delete of the master exercise never rewrites them, so `exerciseId` is a soft link only (null for ad-hoc). Only ever saved nested inside a WorkoutSession (documentation/Architektúra/Backend.md \"Nested aggregate PUT\"), but its own sync row. The enum values match Exercise.yaml\'s category/kind exactly (kept inline here rather than a shared $ref to avoid retyping the already-shipped Exercise model).
 */
export interface WorkoutExerciseEntry { 
    id: string;
    sessionId: string;
    /**
     * → Gyakorlat master (exercise_catalog). Null for ad-hoc; a soft link only.
     */
    exerciseId?: string | null;
    exerciseName: string;
    exerciseCategory: WorkoutExerciseEntry.ExerciseCategoryEnum;
    /**
     * Snapshot of the master ExerciseKind — the set UI fields follow this.
     */
    exerciseKind: WorkoutExerciseEntry.ExerciseKindEnum;
    orderIndex: number;
    /**
     * Same value = visual superset / round group (no per-set superset UI).
     */
    supersetGroup?: number | null;
    sets: Array<WorkoutSetEntry>;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace WorkoutExerciseEntry {
    export const ExerciseCategoryEnum = {
        Chest: 'CHEST',
        Back: 'BACK',
        Legs: 'LEGS',
        Shoulders: 'SHOULDERS',
        Arms: 'ARMS',
        Core: 'CORE',
        ForearmFingers: 'FOREARM_FINGERS',
        FullBody: 'FULL_BODY'
    } as const;
    export type ExerciseCategoryEnum = typeof ExerciseCategoryEnum[keyof typeof ExerciseCategoryEnum];
    export const ExerciseKindEnum = {
        WeightedReps: 'WEIGHTED_REPS',
        BodyweightReps: 'BODYWEIGHT_REPS',
        IsometricTime: 'ISOMETRIC_TIME',
        HangboardPinch: 'HANGBOARD_PINCH',
        CardioTimeDist: 'CARDIO_TIME_DIST'
    } as const;
    export type ExerciseKindEnum = typeof ExerciseKindEnum[keyof typeof ExerciseKindEnum];
}


