/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Heti terv.md \"targetSets\" — one target set on a WorkoutPlanExercise. Same field shape as WorkoutSetEntry minus `setNumber` / `isCompleted` (a template set has no completed state; ordering is `orderIndex` alone). The free `setType` list already expresses the warm-up ramping + few heavy WORKING sets pattern — no separate intensity field. Only ever saved nested inside a WorkoutPlan (documentation/Architektúra/Backend.md \"Nested aggregate PUT\"), but its own sync row. Which measurement fields apply follows the parent\'s `exerciseKind` snapshot; the server persists whatever is sent (deliberately loose type rule).
 */
export interface WorkoutPlanSet { 
    id: string;
    planExerciseId: string;
    setType: WorkoutPlanSet.SetTypeEnum;
    /**
     * Target reps.
     */
    reps?: number | null;
    /**
     * Target load, kg only. Bodyweight = 0; weighted = +kg; assist (band/pulley) = negative kg.
     */
    weightKg?: number | null;
    /**
     * Target isometric / hangboard / time-based / cardio duration.
     */
    holdTimeSeconds?: number | null;
    /**
     * Target hold size in mm (e.g. 20 mm edge, pinch).
     */
    edgeSizeMm?: number | null;
    /**
     * Target cardio distance in metres.
     */
    distanceMeters?: number | null;
    /**
     * Target rest after this set — a long value on a WORKING set signals a heavy effort.
     */
    restTimeSeconds?: number | null;
    orderIndex: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace WorkoutPlanSet {
    export const SetTypeEnum = {
        Warmup: 'WARMUP',
        Working: 'WORKING',
        Dropset: 'DROPSET',
        RestPause: 'REST_PAUSE',
        Failure: 'FAILURE'
    } as const;
    export type SetTypeEnum = typeof SetTypeEnum[keyof typeof SetTypeEnum];
}


