/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * documentation/Subfeatures/Edzésnapló.md \"Entitás — WorkoutSetEntry\" — one set on a WorkoutExerciseEntry. Only ever saved nested inside a WorkoutSession (documentation/Architektúra/ Backend.md \"Nested aggregate PUT\"), but its own sync row (own tombstones, own delta pull entries). Units are kg / mm / m only; assist (band/pulley) is a negative weightKg. Which of the optional measurement fields apply follows the parent entry\'s exerciseKind snapshot; the server persists whatever is sent (deliberately loose type rule).
 */
export interface WorkoutSetEntry { 
    id: string;
    exerciseEntryId: string;
    setNumber: number;
    setType: WorkoutSetEntry.SetTypeEnum;
    reps?: number | null;
    /**
     * kg only. Bodyweight = 0; weighted = +kg; assist (band/pulley) = negative kg.
     */
    weightKg?: number | null;
    /**
     * Isometric / hangboard / time-based / cardio duration.
     */
    holdTimeSeconds?: number | null;
    /**
     * Hold size in mm (e.g. 20 mm edge, pinch).
     */
    edgeSizeMm?: number | null;
    /**
     * Cardio distance in metres (e.g. 1000 m row).
     */
    distanceMeters?: number | null;
    restTimeSeconds?: number | null;
    /**
     * Live mode tick; a skipped set is false or deleted.
     */
    isCompleted: boolean;
    orderIndex: number;
    deleted: boolean;
    readonly deletedAt?: string | null;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export namespace WorkoutSetEntry {
    export const SetTypeEnum = {
        Warmup: 'WARMUP',
        Working: 'WORKING',
        Dropset: 'DROPSET',
        RestPause: 'REST_PAUSE',
        Failure: 'FAILURE'
    } as const;
    export type SetTypeEnum = typeof SetTypeEnum[keyof typeof SetTypeEnum];
}


