export * from './admin.service';
import { AdminService } from './admin.service';
export * from './admin.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './profile.serviceInterface';
export * from './sync.service';
import { SyncService } from './sync.service';
export * from './sync.serviceInterface';
export const APIS = [AdminService, AuthService, HealthService, ProfileService, SyncService];
