/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { AuthTokens } from '../model/models';
import { LoginRequest } from '../model/models';
import { RefreshRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Username + password login. Generic error on failure (doesn\&#39;t reveal which was wrong).
     * 
     * @endpoint post /api/auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<AuthTokens>;

    /**
     * Revoke the given refresh token for the current device.
     * 
     * @endpoint post /api/auth/logout
     * @param refreshRequest 
     */
    logout(refreshRequest: RefreshRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Exchange a valid refresh token for a new access token (with refresh rotation).
     * 
     * @endpoint post /api/auth/refresh
     * @param refreshRequest 
     */
    refresh(refreshRequest: RefreshRequest, extraHttpRequestParams?: any): Observable<AuthTokens>;

}
