/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { AycmCheckIn } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AycmCheckInsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a Check-In — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/aycm-check-ins
     * @param aycmCheckIn 
     */
    createAycmCheckIn(aycmCheckIn: AycmCheckIn, extraHttpRequestParams?: any): Observable<AycmCheckIn>;

    /**
     * Soft delete, idempotent. The day becomes free again.
     * 
     * @endpoint delete /api/aycm-check-ins/{id}
     * @param id 
     */
    deleteAycmCheckIn(id: string, extraHttpRequestParams?: any): Observable<AycmCheckIn>;

    /**
     * A single Check-In. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/aycm-check-ins/{id}
     * @param id 
     */
    getAycmCheckIn(id: string, extraHttpRequestParams?: any): Observable<AycmCheckIn>;

    /**
     * The caller\&#39;s Check-Ins, live rows only (deleted &#x3D; false). Optional from/to narrows by checkInDate (inclusive) for the hub / stats; the Check-In screen itself loads everything and filters locally.
     * 
     * @endpoint get /api/aycm-check-ins
     * @param from 
     * @param to 
     */
    listAycmCheckIns(from?: string, to?: string, extraHttpRequestParams?: any): Observable<Array<AycmCheckIn>>;

    /**
     * Full update (last-write-wins) — the client sends the whole row with a fresh snapshot. Rewriting checkInDate onto a day that already has a live Check-In returns 409 UNIQUE_VIOLATION, same as create.
     * 
     * @endpoint put /api/aycm-check-ins/{id}
     * @param id 
     * @param aycmCheckIn 
     */
    updateAycmCheckIn(id: string, aycmCheckIn: AycmCheckIn, extraHttpRequestParams?: any): Observable<AycmCheckIn>;

}
