/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { BikeRideLog } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BikeRideLogsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a bike ride log — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/bike-ride-logs
     * @param bikeRideLog 
     */
    createBikeRideLog(bikeRideLog: BikeRideLog, extraHttpRequestParams?: any): Observable<BikeRideLog>;

    /**
     * Soft delete, idempotent.
     * 
     * @endpoint delete /api/bike-ride-logs/{id}
     * @param id 
     */
    deleteBikeRideLog(id: string, extraHttpRequestParams?: any): Observable<BikeRideLog>;

    /**
     * A single bike ride log. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/bike-ride-logs/{id}
     * @param id 
     */
    getBikeRideLog(id: string, extraHttpRequestParams?: any): Observable<BikeRideLog>;

    /**
     * The caller\&#39;s bike ride logs, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/bike-ride-logs
     */
    listBikeRideLogs(extraHttpRequestParams?: any): Observable<Array<BikeRideLog>>;

    /**
     * Full update (last-write-wins).
     * 
     * @endpoint put /api/bike-ride-logs/{id}
     * @param id 
     * @param bikeRideLog 
     */
    updateBikeRideLog(id: string, bikeRideLog: BikeRideLog, extraHttpRequestParams?: any): Observable<BikeRideLog>;

}
