/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { BoulderProblem } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClimbingBoulderProblemsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a boulder problem — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/climbing/boulder-problems
     * @param boulderProblem 
     */
    createClimbingBoulderProblem(boulderProblem: BoulderProblem, extraHttpRequestParams?: any): Observable<BoulderProblem>;

    /**
     * Soft delete, idempotent.
     * 
     * @endpoint delete /api/climbing/boulder-problems/{id}
     * @param id 
     */
    deleteClimbingBoulderProblem(id: string, extraHttpRequestParams?: any): Observable<BoulderProblem>;

    /**
     * A single boulder problem. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/climbing/boulder-problems/{id}
     * @param id 
     */
    getClimbingBoulderProblem(id: string, extraHttpRequestParams?: any): Observable<BoulderProblem>;

    /**
     * The caller\&#39;s outdoor boulder problems, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/climbing/boulder-problems
     */
    listClimbingBoulderProblems(extraHttpRequestParams?: any): Observable<Array<BoulderProblem>>;

    /**
     * Full update (last-write-wins).
     * 
     * @endpoint put /api/climbing/boulder-problems/{id}
     * @param id 
     * @param boulderProblem 
     */
    updateClimbingBoulderProblem(id: string, boulderProblem: BoulderProblem, extraHttpRequestParams?: any): Observable<BoulderProblem>;

}
