/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CuratedRoute } from '../model/models';
import { CuratedRouteActivityType } from '../model/models';
import { CuratedRouteDifficulty } from '../model/models';
import { CuratedRouteUpsertRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CuratedRoutesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Admin hard delete, idempotens (backlog/tura-utvonaltervezo/103-... 2.5 fázis). Admin API — X-Admin-Api-Key.
     * 
     * @endpoint delete /api/admin/tura/curated-routes/{id}
     * @param id 
     */
    deleteCuratedRoute(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * backlog/tura-utvonaltervezo/103-... 2.5 fázis — admin-szerkesztett/OSM-eredetű ajánlott túrakatalógus, szűrhető nehézség/aktivitás-típus/táv szerint. Minden szűrő opcionális; szűrő nélkül a teljes katalógust adja vissza.
     * 
     * @endpoint get /api/tura/curated-routes
     * @param difficulty 
     * @param activityType 
     * @param minDistanceMeters 
     * @param maxDistanceMeters 
     */
    listCuratedRoutes(difficulty?: CuratedRouteDifficulty, activityType?: CuratedRouteActivityType, minDistanceMeters?: number, maxDistanceMeters?: number, extraHttpRequestParams?: any): Observable<Array<CuratedRoute>>;

    /**
     * Admin upsert (backlog/tura-utvonaltervezo/103-... 2.5 fázis): a megadott id-re a teljes rekordot létrehozza vagy lecseréli. Admin API — X-Admin-Api-Key.
     * 
     * @endpoint post /api/admin/tura/curated-routes
     * @param curatedRouteUpsertRequest 
     */
    upsertCuratedRoute(curatedRouteUpsertRequest: CuratedRouteUpsertRequest, extraHttpRequestParams?: any): Observable<CuratedRoute>;

}
