/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { DailyStepLog } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DailyStepLogsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a daily step log — idempotent upsert on the client-supplied (deterministic v5) id. A POST for an already-existing or soft-deleted day resolves to / revives that day\&#39;s row.
     * 
     * @endpoint post /api/daily-step-logs
     * @param dailyStepLog 
     */
    createDailyStepLog(dailyStepLog: DailyStepLog, extraHttpRequestParams?: any): Observable<DailyStepLog>;

    /**
     * Soft delete, idempotent.
     * 
     * @endpoint delete /api/daily-step-logs/{id}
     * @param id 
     */
    deleteDailyStepLog(id: string, extraHttpRequestParams?: any): Observable<DailyStepLog>;

    /**
     * A single daily step log. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/daily-step-logs/{id}
     * @param id 
     */
    getDailyStepLog(id: string, extraHttpRequestParams?: any): Observable<DailyStepLog>;

    /**
     * The caller\&#39;s daily step logs, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/daily-step-logs
     */
    listDailyStepLogs(extraHttpRequestParams?: any): Observable<Array<DailyStepLog>>;

    /**
     * Full update (last-write-wins). Max-wins is applied on the client, not here.
     * 
     * @endpoint put /api/daily-step-logs/{id}
     * @param id 
     * @param dailyStepLog 
     */
    updateDailyStepLog(id: string, dailyStepLog: DailyStepLog, extraHttpRequestParams?: any): Observable<DailyStepLog>;

}
