/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { CalendarEvent } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create an event — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/events
     * @param calendarEvent 
     */
    createEvent(calendarEvent: CalendarEvent, extraHttpRequestParams?: any): Observable<CalendarEvent>;

    /**
     * Soft delete, idempotent. Deletes the whole series (no undelete).
     * 
     * @endpoint delete /api/events/{id}
     * @param id 
     */
    deleteEvent(id: string, extraHttpRequestParams?: any): Observable<CalendarEvent>;

    /**
     * A single event. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/events/{id}
     * @param id 
     */
    getEvent(id: string, extraHttpRequestParams?: any): Observable<CalendarEvent>;

    /**
     * The caller\&#39;s events, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/events
     */
    listEvents(extraHttpRequestParams?: any): Observable<Array<CalendarEvent>>;

    /**
     * Full update (last-write-wins). Always applies to the whole series — there is no \&quot;just this occurrence\&quot; (documentation/Features/Események.md \&quot;Modell: egy sor &#x3D; egy sorozat\&quot;).
     * 
     * @endpoint put /api/events/{id}
     * @param id 
     * @param calendarEvent 
     */
    updateEvent(id: string, calendarEvent: CalendarEvent, extraHttpRequestParams?: any): Observable<CalendarEvent>;

}
