/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { Food } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FoodsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a food — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/foods
     * @param food 
     */
    createFood(food: Food, extraHttpRequestParams?: any): Observable<Food>;

    /**
     * Soft delete, idempotent. Cascades to soft-deleting every referencing storage / recipe / shopping-list / meal item, for every user (documentation/Subfeatures/Élelmiszerek.md).
     * 
     * @endpoint delete /api/foods/{id}
     * @param id 
     */
    deleteFood(id: string, extraHttpRequestParams?: any): Observable<Food>;

    /**
     * A single food. Shared catalog — a deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/foods/{id}
     * @param id 
     */
    getFood(id: string, extraHttpRequestParams?: any): Observable<Food>;

    /**
     * The shared food catalog, live rows only (deleted &#x3D; false). Not user-scoped.
     * 
     * @endpoint get /api/foods
     */
    listFoods(extraHttpRequestParams?: any): Observable<Array<Food>>;

    /**
     * Full update (last-write-wins).
     * 
     * @endpoint put /api/foods/{id}
     * @param id 
     * @param food 
     */
    updateFood(id: string, food: Food, extraHttpRequestParams?: any): Observable<Food>;

}
