/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { HouseholdRoom } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HouseholdRoomsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a room — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/household-rooms
     * @param householdRoom 
     */
    createHouseholdRoom(householdRoom: HouseholdRoom, extraHttpRequestParams?: any): Observable<HouseholdRoom>;

    /**
     * Soft delete, idempotent. Cascades to soft-deleting every live HouseholdTask in this room (documentation/Subfeatures/Háztartási feladatok.md).
     * 
     * @endpoint delete /api/household-rooms/{id}
     * @param id 
     */
    deleteHouseholdRoom(id: string, extraHttpRequestParams?: any): Observable<HouseholdRoom>;

    /**
     * A single room. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/household-rooms/{id}
     * @param id 
     */
    getHouseholdRoom(id: string, extraHttpRequestParams?: any): Observable<HouseholdRoom>;

    /**
     * The caller\&#39;s rooms, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/household-rooms
     */
    listHouseholdRooms(extraHttpRequestParams?: any): Observable<Array<HouseholdRoom>>;

    /**
     * Full update (last-write-wins) — rename and/or manual reorder.
     * 
     * @endpoint put /api/household-rooms/{id}
     * @param id 
     * @param householdRoom 
     */
    updateHouseholdRoom(id: string, householdRoom: HouseholdRoom, extraHttpRequestParams?: any): Observable<HouseholdRoom>;

}
