/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { HouseholdTask } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HouseholdTasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a task — idempotent upsert on the client-supplied id. A multi-room create on the client is N independent POSTs, one per room (documentation/Subfeatures/Háztartási feladatok.md).
     * 
     * @endpoint post /api/household-tasks
     * @param householdTask 
     */
    createHouseholdTask(householdTask: HouseholdTask, extraHttpRequestParams?: any): Observable<HouseholdTask>;

    /**
     * Soft delete, idempotent. The room itself is untouched.
     * 
     * @endpoint delete /api/household-tasks/{id}
     * @param id 
     */
    deleteHouseholdTask(id: string, extraHttpRequestParams?: any): Observable<HouseholdTask>;

    /**
     * A single task. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/household-tasks/{id}
     * @param id 
     */
    getHouseholdTask(id: string, extraHttpRequestParams?: any): Observable<HouseholdTask>;

    /**
     * The caller\&#39;s household tasks, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/household-tasks
     */
    listHouseholdTasks(extraHttpRequestParams?: any): Observable<Array<HouseholdTask>>;

    /**
     * Full update (last-write-wins). Completing a task (\&quot;pipálás\&quot;) is a PUT with the client-rolled nextDue / lastCompletedAt (documentation/Subfeatures/Háztartási feladatok.md \&quot;Pipálás\&quot;).
     * 
     * @endpoint put /api/household-tasks/{id}
     * @param id 
     * @param householdTask 
     */
    updateHouseholdTask(id: string, householdTask: HouseholdTask, extraHttpRequestParams?: any): Observable<HouseholdTask>;

}
