/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { LifePlan } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LifePlansServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a life plan — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/life-plans
     * @param lifePlan 
     */
    createLifePlan(lifePlan: LifePlan, extraHttpRequestParams?: any): Observable<LifePlan>;

    /**
     * Soft delete, idempotent. No undelete (documentation/Subfeatures/Élet tervek.md).
     * 
     * @endpoint delete /api/life-plans/{id}
     * @param id 
     */
    deleteLifePlan(id: string, extraHttpRequestParams?: any): Observable<LifePlan>;

    /**
     * A single life plan. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/life-plans/{id}
     * @param id 
     */
    getLifePlan(id: string, extraHttpRequestParams?: any): Observable<LifePlan>;

    /**
     * The caller\&#39;s life plans, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/life-plans
     */
    listLifePlans(extraHttpRequestParams?: any): Observable<Array<LifePlan>>;

    /**
     * Full update (last-write-wins).
     * 
     * @endpoint put /api/life-plans/{id}
     * @param id 
     * @param lifePlan 
     */
    updateLifePlan(id: string, lifePlan: LifePlan, extraHttpRequestParams?: any): Observable<LifePlan>;

}
