/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { PackingSessionItem } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PackingSessionItemsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add an extra item to an already-running session (documentation/Subfeatures/Pakolás.md \&quot;Extra eszköz\&quot;) — idempotent upsert on the client-supplied id. Not part of the session\&#39;s nested create.
     * 
     * @endpoint post /api/packing-session-items
     * @param packingSessionItem 
     */
    createPackingSessionItem(packingSessionItem: PackingSessionItem, extraHttpRequestParams?: any): Observable<PackingSessionItem>;

    /**
     * A single session item. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/packing-session-items/{id}
     * @param id 
     */
    getPackingSessionItem(id: string, extraHttpRequestParams?: any): Observable<PackingSessionItem>;

    /**
     * Full update (last-write-wins) — status change or manual reorder (documentation/Subfeatures/Pakolás.md). No DELETE: items are never removed from the list by the user, only status-changed (and cascade-deleted via the GearItem or the session itself).
     * 
     * @endpoint put /api/packing-session-items/{id}
     * @param id 
     * @param packingSessionItem 
     */
    updatePackingSessionItem(id: string, packingSessionItem: PackingSessionItem, extraHttpRequestParams?: any): Observable<PackingSessionItem>;

}
