/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { PackingTemplate } from '../model/models';
import { PackingTemplateDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PackingTemplatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a template with its items in one request — idempotent upsert on the client-supplied id (documentation/Architektúra/Backend-offline first.md §11 nested aggregate save).
     * 
     * @endpoint post /api/packing-templates
     * @param packingTemplateDetail 
     */
    createPackingTemplate(packingTemplateDetail: PackingTemplateDetail, extraHttpRequestParams?: any): Observable<PackingTemplateDetail>;

    /**
     * Soft delete, idempotent. Cascades to soft-deleting every item on this template.
     * 
     * @endpoint delete /api/packing-templates/{id}
     * @param id 
     */
    deletePackingTemplate(id: string, extraHttpRequestParams?: any): Observable<PackingTemplateDetail>;

    /**
     * The full template tree. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/packing-templates/{id}
     * @param id 
     */
    getPackingTemplate(id: string, extraHttpRequestParams?: any): Observable<PackingTemplateDetail>;

    /**
     * The caller\&#39;s packing templates, live rows only (deleted &#x3D; false), without items.
     * 
     * @endpoint get /api/packing-templates
     */
    listPackingTemplates(extraHttpRequestParams?: any): Observable<Array<PackingTemplate>>;

    /**
     * Full tree replace (documentation/Architektúra/Backend.md \&quot;Nested aggregate PUT\&quot;): items not present in the body are soft-deleted, last-write-wins on the whole aggregate.
     * 
     * @endpoint put /api/packing-templates/{id}
     * @param id 
     * @param packingTemplateDetail 
     */
    updatePackingTemplate(id: string, packingTemplateDetail: PackingTemplateDetail, extraHttpRequestParams?: any): Observable<PackingTemplateDetail>;

}
