/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { RecurringExpense } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RecurringExpensesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a recurring expense — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/recurring-expenses
     * @param recurringExpense 
     */
    createRecurringExpense(recurringExpense: RecurringExpense, extraHttpRequestParams?: any): Observable<RecurringExpense>;

    /**
     * Soft delete, idempotent.
     * 
     * @endpoint delete /api/recurring-expenses/{id}
     * @param id 
     */
    deleteRecurringExpense(id: string, extraHttpRequestParams?: any): Observable<RecurringExpense>;

    /**
     * A single recurring expense. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/recurring-expenses/{id}
     * @param id 
     */
    getRecurringExpense(id: string, extraHttpRequestParams?: any): Observable<RecurringExpense>;

    /**
     * The caller\&#39;s recurring expenses, live rows only (deleted &#x3D; false); inactive rows included.
     * 
     * @endpoint get /api/recurring-expenses
     */
    listRecurringExpenses(extraHttpRequestParams?: any): Observable<Array<RecurringExpense>>;

    /**
     * Full update (last-write-wins). Also the \&quot;Fizetve\&quot; and pause/resume operations — the client sends the whole row with the new nextBillingDate / active. The server does not auto-roll dates.
     * 
     * @endpoint put /api/recurring-expenses/{id}
     * @param id 
     * @param recurringExpense 
     */
    updateRecurringExpense(id: string, recurringExpense: RecurringExpense, extraHttpRequestParams?: any): Observable<RecurringExpense>;

}
