/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { ShoppingList } from '../model/models';
import { ShoppingListCompleteRequest } from '../model/models';
import { ShoppingListCompleteResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShoppingListsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * documentation/Subfeatures/Bevásárlás teljesítve.md — atomic \&quot;Bevásárlás vége\&quot;: creates StoredFood rows for the checked FOOD items, archives this list, and optionally spins off a new active list from the leftover unchecked items. documentation/Architektúra/Backend-offline first.md §11 atomic multi-entity endpoint — replay-safe via the required Idempotency-Key header.
     * 
     * @endpoint post /api/shopping-lists/{id}/complete
     * @param id 
     * @param idempotencyKey 
     * @param shoppingListCompleteRequest 
     */
    completeShoppingList(id: string, idempotencyKey: string, shoppingListCompleteRequest: ShoppingListCompleteRequest, extraHttpRequestParams?: any): Observable<ShoppingListCompleteResponse>;

    /**
     * Create a shopping list with its items in one request — idempotent upsert on the client-supplied id (documentation/Architektúra/Backend-offline first.md §11 nested aggregate save).
     * 
     * @endpoint post /api/shopping-lists
     * @param shoppingList 
     */
    createShoppingList(shoppingList: ShoppingList, extraHttpRequestParams?: any): Observable<ShoppingList>;

    /**
     * Soft delete, idempotent. Cascades to soft-deleting every item on this list.
     * 
     * @endpoint delete /api/shopping-lists/{id}
     * @param id 
     */
    deleteShoppingList(id: string, extraHttpRequestParams?: any): Observable<ShoppingList>;

    /**
     * The full shopping list tree. A soft-deleted list returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/shopping-lists/{id}
     * @param id 
     */
    getShoppingList(id: string, extraHttpRequestParams?: any): Observable<ShoppingList>;

    /**
     * Every live active shopping list (deleted &#x3D; false) owned by the caller, each with its live+tombstoned item rows.
     * 
     * @endpoint get /api/shopping-lists
     */
    listShoppingLists(extraHttpRequestParams?: any): Observable<Array<ShoppingList>>;

    /**
     * Full tree replace (documentation/Architektúra/Backend.md \&quot;Nested aggregate PUT\&quot;): items not present in the body are soft-deleted, last-write-wins on the whole aggregate. &#x60;status&#x60;/ &#x60;completedAt&#x60; are read-only here — see ShoppingList.yaml.
     * 
     * @endpoint put /api/shopping-lists/{id}
     * @param id 
     * @param shoppingList 
     */
    updateShoppingList(id: string, shoppingList: ShoppingList, extraHttpRequestParams?: any): Observable<ShoppingList>;

}
