/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { StoredFood } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StoredFoodsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a storage item — idempotent upsert on the client-supplied id.
     * 
     * @endpoint post /api/stored-foods
     * @param storedFood 
     */
    createStoredFood(storedFood: StoredFood, extraHttpRequestParams?: any): Observable<StoredFood>;

    /**
     * Soft delete, idempotent.
     * 
     * @endpoint delete /api/stored-foods/{id}
     * @param id 
     */
    deleteStoredFood(id: string, extraHttpRequestParams?: any): Observable<StoredFood>;

    /**
     * A single storage item. Own deleted row returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/stored-foods/{id}
     * @param id 
     */
    getStoredFood(id: string, extraHttpRequestParams?: any): Observable<StoredFood>;

    /**
     * The caller\&#39;s home storage inventory, live rows only (deleted &#x3D; false).
     * 
     * @endpoint get /api/stored-foods
     */
    listStoredFoods(extraHttpRequestParams?: any): Observable<Array<StoredFood>>;

    /**
     * Full update (last-write-wins). \&quot;Felbontás\&quot; is a PUT with the client-recomputed opened/openedAt/ expiresOn (documentation/Subfeatures/Élelmiszer tárolás.md \&quot;Felbontás\&quot;).
     * 
     * @endpoint put /api/stored-foods/{id}
     * @param id 
     * @param storedFood 
     */
    updateStoredFood(id: string, storedFood: StoredFood, extraHttpRequestParams?: any): Observable<StoredFood>;

}
