/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RouteMetrics } from '../model/models';
import { RouteMetricsRequest } from '../model/models';
import { RouteSuggestion } from '../model/models';
import { TrailSegment } from '../model/models';
import { TrailSegmentImportRequest } from '../model/models';
import { TrailSegmentImportResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TuraServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Táv/idő/szintkülönbség-becslés + magassági profil egy (kézzel rajzolt vagy automatikusan generált) útvonalhoz (backlog/tura-utvonaltervezo/103-... 2.3 fázis).
     * 
     * @endpoint post /api/tura/route-metrics
     * @param routeMetricsRequest 
     */
    computeRouteMetrics(routeMetricsRequest: RouteMetricsRequest, extraHttpRequestParams?: any): Observable<RouteMetrics>;

    /**
     * Kézi/admin-triggerelt import (backlog/tura-utvonaltervezo/104-...): a megadott országkódra vonatkozó teljes szakaszkészletet lecseréli a kérésben küldött listára. Admin API — X-Admin-Api-Key.
     * 
     * @endpoint post /api/admin/tura/trail-segments/import
     * @param trailSegmentImportRequest 
     */
    importTrailSegments(trailSegmentImportRequest: TrailSegmentImportRequest, extraHttpRequestParams?: any): Observable<TrailSegmentImportResponse>;

    /**
     * Turistaút-szakaszok egy adott ország-kódra és bounding boxra (backlog/tura-utvonaltervezo/103-... 1. fázis). Megosztott referenciaadat, nem user-owned, nem az /api/sync/changes csatornán megy.
     * 
     * @endpoint get /api/tura/trail-segments
     * @param country ISO 3166-1 alpha-2 országkód, pl. \&quot;HU\&quot;.
     * @param minLon 
     * @param minLat 
     * @param maxLon 
     * @param maxLat 
     */
    listTrailSegmentsInBbox(country: string, minLon: number, minLat: number, maxLon: number, maxLat: number, extraHttpRequestParams?: any): Observable<Array<TrailSegment>>;

    /**
     * Automatikus útvonal-javaslat két pont közt a jelzett turistaút-hálózaton (backlog/tura-utvonaltervezo/103-... 2.2 fázis, saját A* a TrailSegment gráfon).
     * 
     * @endpoint get /api/tura/route-suggestion
     * @param country ISO 3166-1 alpha-2 országkód, pl. \&quot;HU\&quot;.
     * @param startLon 
     * @param startLat 
     * @param endLon 
     * @param endLat 
     */
    suggestRoute(country: string, startLon: number, startLat: number, endLon: number, endLat: number, extraHttpRequestParams?: any): Observable<RouteSuggestion>;

}
