/**
 * Life Management 2.0 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { WeeklyPlan } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WeeklyPlansServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a weekly plan with its day slots in one request — idempotent upsert on the client-supplied id (deterministic UUID v5 of userId + weekStartDate, so a POST for an already-existing week resolves to that week\&#39;s row; a soft-deleted row for the same week is revived).
     * 
     * @endpoint post /api/weekly-plans
     * @param weeklyPlan 
     */
    createWeeklyPlan(weeklyPlan: WeeklyPlan, extraHttpRequestParams?: any): Observable<WeeklyPlan>;

    /**
     * Soft delete, idempotent. Cascades to soft-deleting every day slot on this weekly plan.
     * 
     * @endpoint delete /api/weekly-plans/{id}
     * @param id 
     */
    deleteWeeklyPlan(id: string, extraHttpRequestParams?: any): Observable<WeeklyPlan>;

    /**
     * The full weekly plan tree. A soft-deleted weekly plan returns 200 with deleted&#x3D;true (not 404).
     * 
     * @endpoint get /api/weekly-plans/{id}
     * @param id 
     */
    getWeeklyPlan(id: string, extraHttpRequestParams?: any): Observable<WeeklyPlan>;

    /**
     * Every live weekly plan (deleted &#x3D; false) owned by the caller, each with its live+tombstoned day slots.
     * 
     * @endpoint get /api/weekly-plans
     */
    listWeeklyPlans(extraHttpRequestParams?: any): Observable<Array<WeeklyPlan>>;

    /**
     * Full tree replace (documentation/Architektúra/Backend.md \&quot;Nested aggregate PUT\&quot;): slots not present in the body are soft-deleted, last-write-wins on the whole aggregate.
     * 
     * @endpoint put /api/weekly-plans/{id}
     * @param id 
     * @param weeklyPlan 
     */
    updateWeeklyPlan(id: string, weeklyPlan: WeeklyPlan, extraHttpRequestParams?: any): Observable<WeeklyPlan>;

}
