import { addIcons } from 'ionicons';
import {
  addOutline,
  airplaneOutline,
  alertCircle,
  bagHandleOutline,
  barbellOutline,
  businessOutline,
  calendarOutline,
  cartOutline,
  checkboxOutline,
  checkmarkCircleOutline,
  checkmarkDoneOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForwardOutline,
  chevronUpOutline,
  closeOutline,
  cloudOfflineOutline,
  contrastOutline,
  copyOutline,
  createOutline,
  documentTextOutline,
  earthOutline,
  eyeOffOutline,
  eyeOutline,
  flagOutline,
  footstepsOutline,
  helpCircleOutline,
  homeOutline,
  languageOutline,
  listOutline,
  lockClosedOutline,
  logOutOutline,
  menuOutline,
  notificationsOutline,
  personOutline,
  playBackOutline,
  playSkipForwardOutline,
  restaurantOutline,
  settingsOutline,
  squareOutline,
  star,
  starOutline,
  statsChartOutline,
  storefrontOutline,
  syncOutline,
  timeOutline,
  trashOutline,
  walletOutline,
} from 'ionicons/icons';

/**
 * ion-icon's default behaviour resolves icon SVGs over the network (relative to location.href),
 * which fails inside the native WebView's custom scheme ("Failed to construct 'URL': Invalid base
 * URL") — every icon in the app silently renders blank on-device. Registering the SVG data
 * up front via addIcons() avoids the network fetch entirely. Call once at bootstrap, before any
 * component renders.
 */
export function registerIcons(): void {
  addIcons({
    'add-outline': addOutline,
    'airplane-outline': airplaneOutline,
    'alert-circle': alertCircle,
    'bag-handle-outline': bagHandleOutline,
    'barbell-outline': barbellOutline,
    'business-outline': businessOutline,
    'calendar-outline': calendarOutline,
    'cart-outline': cartOutline,
    'checkbox-outline': checkboxOutline,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'checkmark-done-outline': checkmarkDoneOutline,
    'checkmark-outline': checkmarkOutline,
    'chevron-back-outline': chevronBackOutline,
    'chevron-down-outline': chevronDownOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-up-outline': chevronUpOutline,
    'close-outline': closeOutline,
    'cloud-offline-outline': cloudOfflineOutline,
    'contrast-outline': contrastOutline,
    'copy-outline': copyOutline,
    'create-outline': createOutline,
    'document-text-outline': documentTextOutline,
    'earth-outline': earthOutline,
    'eye-off-outline': eyeOffOutline,
    'eye-outline': eyeOutline,
    'flag-outline': flagOutline,
    'footsteps-outline': footstepsOutline,
    'help-circle-outline': helpCircleOutline,
    'home-outline': homeOutline,
    'language-outline': languageOutline,
    'list-outline': listOutline,
    'lock-closed-outline': lockClosedOutline,
    'log-out-outline': logOutOutline,
    'menu-outline': menuOutline,
    'notifications-outline': notificationsOutline,
    'person-outline': personOutline,
    'play-back-outline': playBackOutline,
    'play-skip-forward-outline': playSkipForwardOutline,
    'restaurant-outline': restaurantOutline,
    'settings-outline': settingsOutline,
    'square-outline': squareOutline,
    star: star,
    'star-outline': starOutline,
    'stats-chart-outline': statsChartOutline,
    'storefront-outline': storefrontOutline,
    'sync-outline': syncOutline,
    'time-outline': timeOutline,
    'trash-outline': trashOutline,
    'wallet-outline': walletOutline,
  });
}
